max_execution_time=0
max_input_time=-1
ignore_user_abort=Off
memory_limit=1G
max_memory_limit=-1
#extension=ftp
#extension=intl
#extension=mbstring
#extension=ctype
#extension=apcu
#extension=deepclone
#extension=uuid
